apiVersion: 1
datasources:
  - name: Elasticsearch-Disinfo
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "articles*"
    jsonData:
      esVersion: "8.14.0"
      timeField: processed_at
    isDefault: true
  - name: MongoDB-Disinfo
    type: grafana-mongodb-datasource
    access: proxy
    url: mongodb://mongodb:27017
    jsonData:
      database: disinformation_db
